# Generated by Django 3.2.6 on 2021-12-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_description', models.TextField(blank=True, default='', null=True)),
                ('certificate_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='static/files/')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='education',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='facebook_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='favourite_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extras.category'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='job_role',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='users.Certificate'),
        ),
    ]
