# Generated by Django 3.2.6 on 2021-12-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211203_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='courses_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
