# Generated by Django 3.2.6 on 2021-12-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_instructor_courses_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='student_count',
        ),
    ]
