# Generated by Django 3.2.6 on 2021-12-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_instructor_student_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableForMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True)),
                ('availaibe_for_meetings_from_hour', models.TimeField(blank=True, null=True)),
                ('availaibe_for_meetings_to_hour', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=255)),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hour', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lessons_count', models.PositiveIntegerField(default=0)),
                ('not_studied_lessons_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor')),
                ('off_days', models.ManyToManyField(blank=True, to='users.OffDay')),
                ('subjects', models.ManyToManyField(blank=True, to='users.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='availaibe_for_meetings',
            field=models.ManyToManyField(blank=True, to='users.AvailableForMeeting'),
        ),
    ]
