# Generated by Django 3.2.6 on 2021-12-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_mylearning_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylearning',
            name='progress',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
