# Generated by Django 3.2.6 on 2021-12-12 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20211207_1733'),
        ('users', '0008_mylearning_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylearningcourse',
            name='is_watched',
        ),
        migrations.CreateModel(
            name='MyLearningVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.BooleanField(default=False)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_learning_video', to='courses.video')),
            ],
        ),
        migrations.CreateModel(
            name='MyLearningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_learning_section', to='courses.section')),
                ('videos', models.ManyToManyField(blank=True, to='users.MyLearningVideo')),
            ],
        ),
        migrations.AddField(
            model_name='mylearningcourse',
            name='sections',
            field=models.ManyToManyField(blank=True, to='users.MyLearningSection'),
        ),
    ]
