# Generated by Django 3.2.6 on 2021-12-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211212_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='total_reviews',
            new_name='total_balance',
        ),
    ]
