# Generated by Django 3.2.6 on 2021-12-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_total_reviews_instructor_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='website_role',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('instructor', 'instructor')], default='student', max_length=20, null=True),
        ),
    ]
