# Generated by Django 3.2.6 on 2021-12-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_auto_20211224_1556'),
        ('users', '0011_instructor_website_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylearningcourse',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.instructor'),
        ),
        migrations.AddField(
            model_name='mylearningcourse',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extras.rating'),
        ),
    ]
