# Generated by Django 3.2.6 on 2021-12-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211227_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
