# Generated by Django 3.2.6 on 2021-12-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_schedule_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
