# Generated by Django 3.2.6 on 2021-12-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_availableformeeting_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylearning',
            name='progress',
        ),
        migrations.AddField(
            model_name='mylearningcourse',
            name='progress',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
