# Generated by Django 3.2.6 on 2021-12-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211231_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='note',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='offday',
            name='from_hour',
        ),
        migrations.RemoveField(
            model_name='offday',
            name='to_hour',
        ),
        migrations.AddField(
            model_name='offday',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
