# Generated by Django 3.2.6 on 2021-12-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20211231_1900'),
        ('users', '0018_schedule_number_of_subjects_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='my_tests_as_instructor',
            field=models.ManyToManyField(blank=True, related_name='my_tests_as_instructor', to='courses.CourseTest'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='my_tests_as_students',
            field=models.ManyToManyField(blank=True, related_name='my_tests_as_students', to='courses.MyTest'),
        ),
    ]
