# Generated by Django 3.2.6 on 2022-01-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_availableformeeting_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableformeeting',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_available_time', to='users.instructor'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='availaibe_for_meetings',
            field=models.ManyToManyField(blank=True, related_name='instructor_available_times', to='users.AvailableForMeeting'),
        ),
    ]
