# Generated by Django 3.2.6 on 2022-02-05 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_image', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('category_description', models.TextField(blank=True, default='', null=True)),
                ('students_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('parent_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_category_name', models.CharField(max_length=255)),
                ('parent_category_image', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('parent_category_description', models.TextField(blank=True, default='', null=True)),
                ('students_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ParentCategories',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_provider', models.CharField(choices=[('Visa', 'Visa'), ('Master Card', 'Master Card'), ('Zein Cash', 'Zein Cash')], default='Visa', max_length=20)),
                ('card_number', models.CharField(max_length=16)),
                ('card_cvc', models.PositiveIntegerField(default=123)),
                ('card_expire_date', models.DateField(default='1999-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyAndTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_content', models.TextField(default='')),
                ('rating_value', models.FloatField(default=0)),
                ('likes_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('dislikes_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingLikingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extras.category')),
            ],
        ),
    ]
