# Generated by Django 3.2.6 on 2021-12-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.FileField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='parent_category_image',
            field=models.FileField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
