# Generated by Django 3.2.6 on 2021-12-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_auto_20211218_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='parent_category_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
