# Generated by Django 3.2.6 on 2022-01-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_auto_20220117_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_content',
            field=models.TextField(default=''),
        ),
    ]
