# Generated by Django 3.2.6 on 2021-12-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_auto_20211218_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
