# Generated by Django 3.2.6 on 2022-01-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('message_sent', models.DateTimeField(auto_now_add=True)),
                ('message_delivered', models.DateTimeField(auto_now_add=True)),
                ('message_seen', models.DateTimeField(auto_now_add=True)),
                ('message_is_sent', models.BooleanField(default=True)),
                ('message_is_delivered', models.BooleanField(default=False)),
                ('message_is_seen', models.BooleanField(default=False)),
            ],
        ),
    ]
