# Generated by Django 3.2.6 on 2022-01-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_from', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_to', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbox_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_owner', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.Message'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_room_participants',
            field=models.ManyToManyField(blank=True, to='users.Instructor'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.Message'),
        ),
    ]
