# Generated by Django 3.2.6 on 2022-01-17 13:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', null=True)),
                ('is_correct', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_subtitle', models.CharField(blank=True, max_length=255)),
                ('course_description', models.TextField()),
                ('course_rate', models.FloatField(default=0)),
                ('course_review_count', models.PositiveIntegerField(default=0)),
                ('course_students', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('is_free', models.BooleanField(default=False)),
                ('course_price', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('NONE', 'NONE'), ('USD', 'USD'), ('EURO', 'EURO')], default='2', max_length=255)),
                ('badges', models.CharField(choices=[('Best Selling', 'Best Selling')], default='Best Selling', max_length=255)),
                ('course_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=40)),
                ('course_image', models.FileField(blank=True, upload_to='static/images')),
                ('course_promotional_video', models.FileField(blank=True, upload_to='static/images')),
                ('course_message', models.TextField(blank=True)),
                ('course_language', models.CharField(default='English', max_length=255)),
                ('course_videos_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('course_duration', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('course_selling_times', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('course_tests_price', models.PositiveIntegerField(blank=True, default=25000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goal', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_requirement', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('language', models.CharField(default='English', max_length=255)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=40)),
                ('test_goal', models.TextField(blank=True, default='', null=True)),
                ('test_for', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default='', null=True)),
                ('answer', models.TextField(blank=True, default='', null=True)),
                ('answer_as_image', models.FileField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hour', models.TimeField(blank=True, null=True)),
                ('is_weekly', models.BooleanField(default=False)),
                ('meeting_cover_image', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('day', models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyEditorialQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, default='', null=True)),
                ('answer_as_image', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('is_correct', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyMultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, default='', null=True)),
                ('is_correct', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='static/videos')),
                ('video_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('video_duration', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=255)),
                ('section_article', models.TextField(blank=True, default='', null=True)),
                ('section_videos', models.ManyToManyField(blank=True, related_name='section_videos', to='courses.Video')),
            ],
        ),
        migrations.CreateModel(
            name='MyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_correct', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('course_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursetest')),
            ],
        ),
    ]
