# Generated by Django 3.2.6 on 2021-10-06 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_subtitle', models.CharField(blank=True, max_length=255)),
                ('course_description', models.TextField()),
                ('course_rate', models.FloatField(default=0)),
                ('course_review_count', models.PositiveIntegerField(default=0)),
                ('course_students', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('is_free', models.BooleanField(default=False)),
                ('course_price', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('1', 'NONE'), ('2', 'USD'), ('3', 'EURO')], default='2', max_length=255)),
                ('badges', models.CharField(choices=[('1', 'Best Selling')], default='1', max_length=255)),
                ('course_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=40)),
                ('course_image', models.FileField(blank=True, upload_to='static/images')),
                ('course_promotional_video', models.FileField(blank=True, upload_to='static/images')),
                ('course_requirements', models.TextField(blank=True)),
                ('course_message', models.TextField(blank=True)),
                ('course_language', models.CharField(default='English', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='static/videos')),
                ('video_duration', models.FloatField(default=0)),
            ],
        ),
    ]
