# Generated by Django 3.2.6 on 2021-10-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('extras', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_instructor', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='stream',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.video'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_videos',
            field=models.ManyToManyField(blank=True, related_name='section_videos', to='courses.Video'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrolled', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user_enrolling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_enrolling', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ManyToManyField(blank=True, to='extras.Category'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_parent_category',
            field=models.ManyToManyField(blank=True, to='extras.ParentCategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_sections',
            field=models.ManyToManyField(blank=True, related_name='course_sections', to='courses.Section'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='extras.topic'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_coupon', to='courses.course'),
        ),
    ]
