# Generated by Django 3.2.6 on 2021-11-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='badges',
            field=models.CharField(choices=[('Best Selling', 'Best Selling')], default='Best Selling', max_length=255),
        ),
    ]
