# Generated by Django 3.2.6 on 2021-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goal', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('NONE', 'NONE'), ('USD', 'USD'), ('EURO', 'EURO')], default='2', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='course_learning_goals',
            field=models.ManyToManyField(blank=True, to='courses.CourseLearningGoal'),
        ),
    ]
