# Generated by Django 3.2.6 on 2021-12-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211125_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_videos_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
