# Generated by Django 3.2.6 on 2021-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_videos_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
