# Generated by Django 3.2.6 on 2021-12-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
