# Generated by Django 3.2.6 on 2021-12-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goal', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_requirements',
        ),
        migrations.AddField(
            model_name='course',
            name='course_requirements',
            field=models.ManyToManyField(blank=True, to='courses.CourseRequirement'),
        ),
    ]
