# Generated by Django 3.2.6 on 2021-12-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20211201_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserequirement',
            name='learning_goal',
        ),
        migrations.AddField(
            model_name='courserequirement',
            name='course_requirement',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
