# Generated by Django 3.2.6 on 2021-12-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20211201_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_selling_times',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
