# Generated by Django 3.2.6 on 2021-12-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20211207_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
