# Generated by Django 3.2.6 on 2021-12-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_tests_price',
            field=models.PositiveIntegerField(blank=True, default=25000, null=True),
        ),
    ]
