# Generated by Django 3.2.6 on 2021-12-25 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_total_reviews_instructor_total_balance'),
        ('courses', '0013_course_course_tests_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetest',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor'),
        ),
    ]
