# Generated by Django 3.2.6 on 2021-12-25 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_auto_20211224_1556'),
        ('courses', '0014_coursetest_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', null=True)),
                ('is_correct', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='coursetest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extras.category'),
        ),
        migrations.AddField(
            model_name='coursetest',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='coursetest',
            name='language',
            field=models.CharField(default='English', max_length=255),
        ),
        migrations.AddField(
            model_name='coursetest',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=40),
        ),
        migrations.AddField(
            model_name='coursetest',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='coursetest',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extras.parentcategory'),
        ),
        migrations.AddField(
            model_name='coursetest',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='courses.CourseRequirement'),
        ),
        migrations.AddField(
            model_name='coursetest',
            name='test_for',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='coursetest',
            name='test_goal',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='answers',
            field=models.ManyToManyField(blank=True, to='courses.Answer'),
        ),
    ]
