# Generated by Django 3.2.6 on 2021-12-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20211226_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_article',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
