# Generated by Django 3.2.6 on 2021-12-31 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_schedule_number_of_subjects_per_day'),
        ('courses', '0016_section_section_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEditorialQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, default='', null=True)),
                ('is_correct', models.BooleanField(blank=True, default=False, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.editorialquestion')),
            ],
        ),
        migrations.CreateModel(
            name='MyMultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, default='', null=True)),
                ('is_correct', models.BooleanField(blank=True, default=False, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.multiplechoicequestion')),
            ],
        ),
        migrations.CreateModel(
            name='MyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_correct', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('course_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursetest')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor')),
                ('my_edot_ques_answers', models.ManyToManyField(to='courses.MyEditorialQuestion')),
                ('my_multi_choice_ques_answers', models.ManyToManyField(to='courses.MyMultipleChoiceQuestion')),
            ],
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='data',
            new_name='date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='day',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_cover_image',
            field=models.FileField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.Instructor'),
        ),
        migrations.DeleteModel(
            name='SingleMeeting',
        ),
    ]
