# Generated by Django 3.2.6 on 2022-01-07 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20211231_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_tests',
        ),
        migrations.AddField(
            model_name='course',
            name='course_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_tests', to='courses.coursetest'),
        ),
    ]
