# Generated by Django 3.2.6 on 2022-01-17 13:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart_item_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_owner', to='users.instructor')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('branches', models.ManyToManyField(blank=True, to='orders.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCompanyCutOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.paymentcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('money_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_usable', models.BooleanField(blank=True, default=False, null=True)),
                ('region', models.CharField(blank=True, default='Damascus', max_length=1000, null=True)),
                ('number_sent_to', models.CharField(blank=True, default='Damascus', max_length=1000, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='TempWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('check_image', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('transaction_choice', models.CharField(blank=True, choices=[('add_money', 'add_money'), ('cut_off_money', 'cut_off_money')], default='add_money', max_length=255, null=True)),
                ('number', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('region', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('money_before_edit', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.branch')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor')),
                ('payment_company_cut_off', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.paymentcompanycutoff')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('cart_items', models.ManyToManyField(blank=True, to='orders.CartItem')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_items', models.ManyToManyField(blank=True, to='orders.CartItem')),
                ('cart_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_owner', to='users.instructor')),
            ],
        ),
    ]
