# Generated by Django 3.2.6 on 2021-12-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211207_1733'),
        ('orders', '0002_auto_20211206_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('money_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_usable', models.BooleanField(blank=True, default=False, null=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='TempWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.wallet')),
            ],
        ),
    ]
