# Generated by Django 3.2.6 on 2021-12-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211207_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='number_sent_to',
            field=models.CharField(blank=True, default='Damascus', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='region',
            field=models.CharField(blank=True, default='Damascus', max_length=1000, null=True),
        ),
    ]
