# Generated by Django 3.2.6 on 2021-12-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211220_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempwallet',
            name='check_image',
            field=models.FileField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
