# Generated by Django 3.2.6 on 2021-12-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_tempwallet_check_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempwallet',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
