# Generated by Django 3.2.6 on 2021-12-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_total_reviews_instructor_total_balance'),
        ('orders', '0006_auto_20211226_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('branches', models.ManyToManyField(blank=True, to='orders.Branch')),
            ],
        ),
        migrations.RemoveField(
            model_name='tempwallet',
            name='wallet',
        ),
        migrations.AddField(
            model_name='tempwallet',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor'),
        ),
        migrations.AddField(
            model_name='tempwallet',
            name='transaction_choice',
            field=models.CharField(blank=True, choices=[('add_money', 'add_money'), ('cut_off_money', 'cut_off_money')], default='add_money', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PaymentCompanyCutOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.paymentcompany')),
            ],
        ),
        migrations.AddField(
            model_name='tempwallet',
            name='payment_company_cut_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.paymentcompanycutoff'),
        ),
    ]
