# Generated by Django 3.2.6 on 2021-12-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_tempwallet_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempwallet',
            name='region',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
